package gui;

import javax.swing.JTextField;
import model.App;

/**
 *
 * @author Anabel
 */
public class ShowOutputWindow extends javax.swing.JFrame {
    double irt;
    public static final String[] clas = new String[]{
        "Riesgo trivial",
        "Riesgo tolerable",
        "Riesgo moderado",
        "Riesgo importante",
        "Riesgo intolerable"
    };
    public static final String[] message = new String[]{
              "No se requiere acción específica",
              "No se necesita mejorar la acción preventiva,\n"
            + "sin embargo se deben considerar soluciones más\n"
            + "rentables o mejoras que no supongan una carga\n"
            + "económica importante. Se requieren comprobaciones\n"
            + "periódicas para asegurar que se mantiene la eficacia\n"
            + "de las medidas de control.",
              "Se deben hacer esfuerzos para reducir el riesgo,\n"
            + "determinando las inversiones precisas, las medidas\n"
            + "deben implementarse en un período determinado.",
              "Se deben hacer esfuerzos para reducir el riesgo,\n"
            + "determinando las inversiones precisas, las medidas\n"
            + "deben implementarse en un período determinado.",
              "No debe comenzar ni continuar el trabajo hasta que\n"
            + "se reduzca el riesgo, si esto no es posible, incluso\n"
            + "con recursos ilimitados, debe prohibirse el trabajo."
    };   
    
    public JTextField getOutputTextField() {
        return outputTextField;
    }
    
    public void setIrt(double irt) {
        this.irt = irt;
    }
    
    public void showOutput(){
        int index = 0;        
        if(irt < 0.025){
            index = 0;       
        }
        else{
            if(irt < 0.10){
                index = 1;
            }
            else{
                if(irt < 0.29){
                    index = 2;
                }
                else{
                    if(irt < 0.57){
                        index = 3;
                    }
                    else{
                        index = 4;
                    }
                }
            }
        }
            
        outputTextField.setText(String.format("%.3f", irt));
        clasTextField.setText(clas[index]);
        messageTextArea.setText(message[index]);        
        App.setCentered(this);
        setVisible(true);
    }
    
    /**
     * Creates new form ShowOutputWindow
     */
    public ShowOutputWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        outputTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        clasTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageTextArea = new javax.swing.JTextArea();

        setTitle("Resultados");
        setAlwaysOnTop(true);
        setResizable(false);

        jLabel1.setText("Valor del IRT:");

        outputTextField.setEditable(false);
        outputTextField.setToolTipText("Indice de riesgo tecnológico");
        outputTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputTextFieldActionPerformed(evt);
            }
        });

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Evaluación:");

        clasTextField.setEditable(false);
        clasTextField.setToolTipText("Evaluación según el IRT");

        jLabel3.setText("Acciones:");

        messageTextArea.setEditable(false);
        messageTextArea.setColumns(20);
        messageTextArea.setLineWrap(true);
        messageTextArea.setRows(5);
        jScrollPane1.setViewportView(messageTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(outputTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(clasTextField))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(outputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(82, 82, 82))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void outputTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputTextFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField clasTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea messageTextArea;
    private javax.swing.JTextField outputTextField;
    // End of variables declaration//GEN-END:variables
}
